name: bt2ir
description: Application working as remote controller for TV.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  convert: ^3.1.1
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.25.1
  fluttertoast: ^8.2.2
  location: ^4.4.0
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
